### ISSUE TITLE
What Odoo version does it apply to?

### ISSUE THREAD

**Issue by smonff** [amlaksil/Odoo-JSON-RPC-API#2]
Please, can you specify which Odoo version your examples apply to?

**Comment by smonff** [comment]
By the way, thank you so much for that. It should be merged to Odoo official documentation.

**Comment by amlaksil** [comment]
I've tested this on Odoo version 15.0. If you're using a different version, there might be some differences in certain features or functionalities, but the underlying logic generally applies to other Odoo versions as well. Let me know if you need any further assistance!

**Comment by amlaksil** [comment]
> By the way, thank you so much for that. It should be merged to Odoo official documentation.

You're welcome! I'm glad it was helpful.

**Comment by smonff** [comment]
> I've tested this on Odoo version 15.0. If you're using a different version, there might be some differences in certain features or functionalities, but the underlying logic generally applies to other Odoo versions as well. Let me know if you need any further assistance!

Thanks! There is no issue… I'm converting a system from XML-RPC to JSON-RPC, and your examples just helped me to understand how things, actually work. I really dislike Odoo official documentation.

Seem to work with Odoo 17.
